### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by alabazazzade** [abhilashmnair/Sarcasm-Detection-with-BERT-and-GCN#2]
i get the error below when my device is cuda after one Epoch. 

python train.py
loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at C:\Users\USER\.pytorch_pretrained_bert\26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at C:\Users\USER\.pytorch_pretrained_bert\9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
extracting archive file C:\Users\USER\.pytorch_pretrained_bert\9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir C:\Users\USER\AppData\Local\Temp\tmprqn_02ta
Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

cuda memory allocated: 448517632
> n_trainable_params: 111846146, n_nontrainable_params: 0
> training arguments:
>>> model_name: bertgcn
>>> dataset: headlines
>>> optimizer: <class 'torch.optim.adam.Adam'>
>>> initializer: <function xavier_uniform_ at 0x0000027C878CCB70>
>>> lr: 2e-05
>>> dropout: 0.1
>>> l2reg: 1e-05
>>> num_epoch: 30
>>> batch_size: 16
>>> log_step: 20
>>> embed_dim: 100
>>> hidden_dim: 768
>>> bert_dim: 768
>>> pretrained_bert_name: bert-base-uncased
>>> max_seq_len: 85
>>> polarities_dim: 2
>>> hops: 3
>>> patience: 5
>>> device: cuda
>>> seed: 776
>>> valset_ratio: 0
>>> model_class: <class 'models.bertgcn.BERTGCN'>
>>> dataset_file: {'train': './datasets/headlines/train.raw', 'test': './datasets/headlines/test.raw'}
>>> inputs_cols: ['text_bert_indices', 'bert_segments_indices', 'dependency_graph', 'affective_graph']
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Epoch : 1
Loss : 0.7858, Accuracy : 0.5219
Loss : 0.7584, Accuracy : 0.5203
Loss : 0.7384, Accuracy : 0.5198
Loss : 0.7141, Accuracy : 0.5469
Loss : 0.6845, Accuracy : 0.5850
Loss : 0.6539, Accuracy : 0.6198
Loss : 0.6284, Accuracy : 0.6438
Traceback (most recent call last):
  File "train.py", line 272, in <module>
    main()
  File "train.py", line 269, in main
    ins.run()
  File "train.py", line 184, in run
    best_model_path = self._train(criterion, optimizer, self.train_data_loader, self.val_data_loader)
  File "train.py", line 120, in _train
    val_acc, val_f1 = self._evaluate_acc_f1(val_data_loader)
  File "train.py", line 173, in _evaluate_acc_f1
    f1 = metrics.f1_score(t_targets_all.cpu(), torch.argmax(t_outputs_all, -1).cpu(), labels = np.unique(torch.argmax(t_outputs_all, -1)), average='macro')
  File "<__array_function__ internals>", line 6, in unique
  File "C:\Users\USER\miniconda3\envs\tfbertsarc\lib\site-packages\numpy\lib\arraysetops.py", line 259, in unique
    ar = np.asanyarray(ar)
  File "C:\Users\USER\miniconda3\envs\tfbertsarc\lib\site-packages\numpy\core\_asarray.py", line 136, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "C:\Users\USER\miniconda3\envs\tfbertsarc\lib\site-packages\torch\_tensor.py", line 678, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by abhilashmnair** [comment]
Hi, @alabazazzade can you use the below code change for the `train.py` file? I had used a non-GPU machine for the training and overlooked the conversion. Add the conversion for `np.unique()` too. I think this should probably solve your issue.

Change at line: https://github.com/abhilashmnair/Sarcasm-Detection-with-BERT-and-GCN/blob/e8682f8475141f9ad980a3e625aee55e65c75221/train.py#L173

```
f1 = metrics.f1_score(
    t_targets_all.cpu(),  # Move the target tensor to the CPU
    torch.argmax(t_outputs_all, -1).cpu(),  # Move output tensor to the CPU
    labels=np.unique(torch.argmax(t_outputs_all.cpu(), -1)),  # Ensure unique labels are computed on the CPU
    average='macro'
)
```

**Comment by abhilashmnair** [comment]
This issue has been addressed.
https://github.com/abhilashmnair/Sarcasm-Detection-with-BERT-and-GCN/commit/df57216e231baf5ded6a423a58e8236476b5422a

**Comment by alabazazzade** [comment]
hi @abhilashmnair, yes that resolves the issue. Also, your code is super clean. I hadn't seen such a great clean and to the point code and paper in ages.

**Comment by abhilashmnair** [comment]
thanks a lot! 🙏
